# Generated by Django 4.0.6 on 2022-08-17 11:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0006_author_book_count_book_price_authorbook'),
    ]

    operations = [
        migrations.AddField(
            model_name='book',
            name='authors',
            field=models.ManyToManyField(to='home.author'),
        ),
        migrations.DeleteModel(
            name='AuthorBook',
        ),
    ]
